package id.ac.poliban.mi.cahyo.listpahlawan;

import android.widget.ListView;

import java.util.ArrayList;
import java.util.List;

public class PahlawanData {
    static List<Pahlawan> getAllPahlawan(){
        List<Pahlawan> data = new ArrayList<>();
        {
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Ir.-Soekarno-300x171.jpg", "Ir.Soekarno", "Soekarno atau yang lebih sering disebut Sukarno merupakan presiden pertama di Indonesia. Beliau mendapa sebutan sebagai bapak proklamator kemerdekaan Indonesia yang diselenggarakan pada tanggal 17 Agustus 1945. Sukarno lahir di Surabaya pada tanggal 6 Juni tahun 1901. Dikenal sebagai orator terbaik yang cerdas, Sukarno mampu menciptakan semangat nasional. Selama masa-masa penting Indonesia, Sukarno pernah mencetuskan negara Pancasila, sehingga terciptalah konsep dasar negara bernama Pancasila yang digunakan Indonesia sampai saat ini."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Mohammad-Hatta-300x169.jpg", "Mohammad Hatta", "Mohammad Hatta adalah salah satu pahalawan Indonesia yang juga dipanggil sebagai Bung Hatta. Bung Hatta adalah seorang wakil presiden Ir. Sukarno yang lahir pada tanggal 12 Agustus 1902 tepatnya di kota Bukittinggi. Bersama Bung Karno, Mohammad Hatta mendapat gelar sebagai Pahlawan Proklamator. Selama menjabat sebagai wakil presiden, Mohammad Hatta banyak menulis tentang ilmu koperasi. Sehingga perannya tersebut mendapat julukan ‘Bapak Koperasi’."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Jenderal-Sudirman-300x189.jpg", "Jenderal Sudirman", "Pahlawan Nasional berikutnya adalah Jenderal Sudirman. Beliau adalah panglima tentara pertama Republik Indonesia dengan jabatan Jenderal Besar TNI Anumerta Sudirman yang sudah memperoleh gelar Jenderalnya pada usia 31 tahun. Jenderal Sudirman sangat berjasa dalam perjuangan di masa penting Revolusi Nasional Indonesia. Pahlawan yang terkenal akan perang gerilya dan Serang Umum 1 Maret tahun 1949 ini lahir di Purbalingga provinsi Jawa tengah pada tanggal 24 Januari di tahun 1916."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Pangeran-Diponegoro-300x150.jpg", "Pangeran Diponogoro", "Pangeran Diponegoro adalah putra pertama dari Raja Mataram, Sultan Hamengkubuwono III. Nama asli Pangeran Diponegoro adalah Mustahar yang lahir di Yogyakarta tepatnya pada tanggal 11 November 1785. Beliau mendapat julukan Pangeran Diponegoro karena telah memimpin perang Diponegoro yang terjadi pada tahun 1825 hingga 1830 antara rakyat Indonesia dengan pemerintah Hindia-Belanda."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2019/05/Biografi-Cut-Nyak-Dien-Singkat-Sejarah.jpg", "Cut Nyak Dien", "Cut Nyak Dhien adalah seorang pahlawan nasional Indonesia yang dilahirkan di Lampadag, Kerajaan Aceh pada tahun 1848. Merupakan salah satu pahlawan wanita yang memiliki semangat perjuangan untuk melawan penjajah Belanda. Cut Nyak Dhien adalah istri seorang pahlawan Indonesia bernama Teuku Umar yang gugur di medan perang tepatnya pada tanggal 11 Januari 1899. Cut Nyak Dhien wafat akibat sakit yang dideritanya dan karena usia. Beliau dimakamkan di Sumedang pada tanggal 6 November tahun 1908."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2019/06/Uang-Kertas-Martha-Christina-Tiahahu.jpg", "Martha Christina Tiahahu", "Seorang gadis desa yang berasal dari Nusa Laut, Maluku ini merupakan salah satu pahlawan nasional yang patut dikenang karena perjuangannya. Martha Christina Tiahahu yang lahir pada tanggal 4 Januari di tahun 1800 ini dikenal sebagai sosok perempuan yang berani karena saat usia 17 tahun ia sudah berani mengangkat senjata dan mengambil bagian dalam perlawanan dengan para penjajah Belanda."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Tuanku-Imam-Bonjol-300x194.jpg", "Tuanku Imam Bonjol", "Seorang ulama yang berasal dari Sumatera Barat ini dikenal karena beberapa gelar seperti Peto Syarif dan Malin Basa. Beliau adalah pemimpin perang Padri (1803-1838). Tuanku Imam Bonjol dilahirkan di Bonjol Sumatera Barat pada 1772 yang ditunjuk sebagai pemimpun kaum Padri di kota Bonjol sehingga ia dijuluki Tuanku Imam Bonjol. Semasa perjuangannya, beliau pernah diasingkan hingga wafat lalu dimakamkan di Minahasa pada tanggal 6 November tahun 1864."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Ki-Hajar-Dewantara-273x300.jpg", "Ki Hajar Dewantara", "Ki Hajar Dewantara yang mempunyai nama asli Raden Mas Soewardi Soerjaningrat ini lahir pada tanggal 2 Mei 1889. Beliau adalah pahlawan dari Yogyakarta yang merupakan salah satu aktivis pergerakan kemerdekaan, politisi, maupun pelopor di bidang pendidikan hingga dikenal dengan semboyan Tut Wuru Handayani. Ki Hajar Dewantara juga dikenal sebagai pendiri lembaga Pendidikan untuk Pribumi yang benama Taman Siswa."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Bung-Tomo-300x230.jpg", "Bung Tomo", "Seorang pahlawan yang berasal dari Surabaya ini bernama Sutomo atau dikenal dengan panggilan Bung Tomo. Beliau terkenal dengan semangat membara pada pertempuran sengit di Surabaya tanggal 10 November 1945. Semboyannya yang sangat terkenal dan berhasil mengobarkan semangat pejuang lain adalah “Merdeka atau mati”. Pertempuran tanggal 10 November tersebut hingga kini dijadikan sebagai Hari Pahlawan Nasional."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Pattimura.jpg", "Pattimura", "Pattimura atau dikenal dengan Kapitan Pattimura mempunyai nama asli Thomas Matulessy. Kapitan Pattimura lahir di Maluku pada tanggal 8 Juni tahun 1783. Ia dikenal sebagai pemimpin pasukan pada peperangan-peperangan besar salah satunya perang tahun 1817. Pattimura juga mampu menyatukan semangat dari kerajaan Ternate hingga Tidore. Perang yang paling terkenal adalah perang Pattimura yang sangat ganas."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Achmad-Soebardjo.jpg", "Achmad Soebardjo", "Pahlawan Indonesia ini memiliki nama lengkap Mr. Raden Achmad Soebardjo Djojoadisoerjo. Beliau lahir pada tanggal 23 Maret 1896 di Karawang, Jawa Barat dan meninggal pada umur 82 tahun pada bulan Desember 1978. Achmad Soebardjo merupakan tokoh pejuang kemerdekaan Indonesia, seorang diplomat dan seorang Pahlawan Nasional Indonesia. Ia menjabat sebagai Menteri Luar Negeri Indonesia yang pertama kali. Gelarnya didapat dari Universitas Leiden Belanda pada tahun 1993 dengan gelar Meester."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Sultan-Iskandar-Muda.jpg", "Sultan Iskandar Muda", "Pahlawan yang berasal dari Aceh, sama seperti Cut Nyak Meutia. Sultan Iskandar Muda adalah salah sultan terbesar dalam masa Kesultanana Aceh, dimana masa berkuasanya adalah dari tahun 1607 hingga 1636. Aceh sendiri mencapai masa kejayaannya pada masa kepemimpinan beliau, dimana Aceh berkembang menjadi besar dan reputasi internasionalnya dijadikan sebagai pusat perdagangan dan pembelajaran tentang agama Islam. Namanya saat ini diabadikan menjadi nama Bandar Udara Internasional di Aceh."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Panglima-Polim.jpeg", "Panglima Polim", "Pemilik nama lengkap Teuku Panglima Polem Sri Muda Perkasa Muhammad Daud ini adalah seorang panglima dari Aceh. Sampai saat ini belum ditemukannya keterangan secara jelas kapan tanggal beliau lahir, yang jelas beliau berasal dari keturunan kaum bangsawan Aceh. Ayahnya bernama Panglima Polem VIII yang merupakan Raja Kuala. Kakek dari Panglima Plem Sri Muda Perkasa Muhammad Daud bernama Teuku Panglima Polem Sri Imam Muda Mahmud Arifin atau biasa dikenal sebagai Cut Banta."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Teuku-Muhammad-Hasan.jpg", "Teuku Muhammad Hasan", "Pahlawan Teuku Muhammad Hasan merupakan Gubernur wilayah Sumatera yang pertama kali setelah Indonesia merdeka. Beliau juga menjabat sebagai Menteri Pendidikan dan Kebudayaan Indonesia pada tahun 1948 sampai 1949 di Kabinet Darurat. Disamping itu, beliau juga seorang pejuang kemerdekaan dan juga pahlawan Indonesia."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Teuku-Umar-278x300.jpg", "Teuku Umar", "Mungkin ketika SD kita sering mendengar namanya dengan nama belakang Meulaboh. Sebenarnya Meulaboh adalah nama tempat beliau lahir. Teuku Umar lahir pada tahun 1854 dan wafat pada tanggal 11 Februari 1899 di Meulaboh juga. Teukur Umar berjuang melawan Belanda dengan cara berpura pura bekerjasama dengan Belanda dan kemudian melawannya setelah berhasil mengumpulkan senjata dan uang cukup banyak."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Teuku-Chik-di-Tiro.jpg", "Teuku Chik di Tiro", "Teuku Cik di Tiro memiliki nama lengkap Teuku Chik di Tiro Muhammad Saman lahir di Pidie pada tahun 1836 dan meninggal pada Januari 1891 di Aneuk Galong, Aceh Besar. Beliau adalah seoerang pahlawan nasional Indonesia yang berasal dari Aceh."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Sultan-Ageng-Tirtayasa-200x300.jpg", "Sultan Ageng Tirtayasa", "Sultan Ageng Tirtayasa lahir di Banten pada tanggal tahun 1631 dan meninggal pada tahun 1683. Beliau adalah putra dari Sultan Abdul Ma’ali Ahmad dan Ratu Martakusuma. Sultan Ageng Tirtayasa menjadi sultan Banten yaitu pada periode 1640 sampai 1650. Saat kecil beliau di beri gelar Pangeran Surya."));
            data.add(new Pahlawan("https://jagad.id/wp-content/uploads/2018/02/Raden-Dewi-Sartika.jpg", "Raden Dewi Sartika", "Raden Dewi Sartika lahir pada tanggal 4 Desember 1884 di Bandung dan meninggal di Tasikmalaya pada tanggal 11 September 1947 pada umur 62 tahun. Beliau merupakan tokoh perintis pendidikan untuk kaum wanita dan diakui sebagai pahlawan Nasional Indonesia pada tahun 1966."));
        }
        return data;
    }
}
